### ISSUE TITLE
Code bug in TestsetLoader?

### ISSUE THREAD

**Issue by ProNoobLi** [LongguangWang/SOF-VSR#14]
Hi, Nice work

I found a confusing part of your TestsetLoader.
![image](https://user-images.githubusercontent.com/33815430/85244632-d839dc80-b477-11ea-9c8b-e63f9545bc68.png)
You normalize the LR tensors twice. One is in the code /255, then .div(255) again in toTensor()
![image](https://user-images.githubusercontent.com/33815430/85244802-526a6100-b478-11ea-9da3-6d75969b3e3f.png)

I don't think it make sense.

**Comment by LongguangWang** [comment]
Hi, thanks for your interest in our work.

**Comment by LongguangWang** [comment]
Hi, thanks for your interest in our work. 
The code `img.float().div(255)` should be removed during the cleanup and I've just fixed it. Note that, `.div()` is not an in-place operation like `.div_()`. That is, this part of code has no effects on the tensor `img` since there is no assignment operation. Therefore, LR tensors are only normalized once.
