### ISSUE TITLE
About the draft cube (input to SRnet)

### ISSUE THREAD

**Issue by musicrainie** [LongguangWang/SOF-VSR#7]
According to the paper, the draft cube should be HxWx(2ss+1) instead of HxWx(2ss+3) in the code, which concatenates not just the central LR frame and can be fixed by changing the following line
https://github.com/LongguangWang/SOF-VSR/blob/420390814ec5d0c3af6678b0773e87ca13279853/modules.py#L172
to
    "draft_cube = torch.unsqueeze(x[:, 1, :, :], dim=1)".
Does it matter to the performance?

**Comment by LongguangWang** [comment]
Thank you for your attention to our work.
As mentioned in README.md, we made some modifications to the original code including this one. We made this modification because we found that adding these two more channels leads to a faster convergence in our experiments. However, this modification does not matter to the performance. In our experiments, the performance is still comparable to the original one without significant improvement.

**Comment by musicrainie** [comment]
Ok, thanks, for your great work and nice code.
